In [1]:
import jax
import jax.numpy as jnp
from jaxlie import SE3, SO3

from sdf_world.sdf_world import *
from sdf_world.robots import *
from sdf_world.util import *

from network import *
from loss import *

In [2]:
world = SDFWorld()
world.show_in_jupyter()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7003/static/


In [3]:
panda_model = RobotModel(PANDA_URDF, PANDA_PACKAGE)
panda = Robot(world.vis, "panda", panda_model, alpha=0.5)
frame = Frame(world.vis, "frame", 0.1)

concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts
concatenating texture: may result in visual artifacts


In [27]:
shoulder = Sphere(world.vis, "shoulder", 0.07, "blue", alpha=0.5)
elbow = Sphere(world.vis, "elbow", 0.07, "red", alpha=0.5)
wrist = Sphere(world.vis, "wrist", 0.07, "green", alpha=0.5)
point = Sphere(world.vis, "point", 0.04, "yellow", 0.6)

In [366]:
def show_fk(q):
    fks = panda_model.fk_fn(q)
    p_shoulder = fks[1][-3:]
    p_elbow = fks[4][-3:]
    p_wrist = fks[5][-3:]
    ee_pose = SE3(fks[-1])
    shoulder.set_translate(p_shoulder)
    elbow.set_translate(p_elbow)
    wrist.set_translate(p_wrist)
    frame.set_pose(ee_pose)
    if q.shape[0] == 7:
        q = jnp.hstack([q, 0.04, 0.04])
    panda.set_joint_angles(q)

In [367]:
show_fk(panda_model.neutral)

In [120]:
fks = panda_model.fk_fn(panda_model.neutral)
p_shoulder = fks[1][-3:]
p_elbow = fks[4][-3:]
p_wrist = fks[5][-3:]
p_ee = fks[-1][-3:]
upper_arm_len = jnp.linalg.norm(p_elbow-p_shoulder)
hand_len = jnp.linalg.norm(p_wrist - p_ee)
lower_arm_len = jnp.linalg.norm(p_elbow-p_wrist)
sphere_points = fibonacci_sphere(1000)
#sphere_points_rtp = jax.vmap(to_spherical_coord)(sphere_points)
shoulder_sphere_points = sphere_points * upper_arm_len + p_shoulder
ee_sphere_points = sphere_points * hand_len
ws_lb, ws_ub = [-1, -1, -0.5], [1, 1, 1.5]


In [44]:
ee_pose = SE3(x[:7])
ee_z = ee_pose.as_matrix()[:3, 2]
p_elbow = x[7:10]
p_wrist = x[10:13]

In [264]:
def rotate_point_by_yaw(pose, point, yaw):
    point_wrt_pose = pose.inverse() @ point
    rotated_pose = pose @ SE3.from_rotation(SO3.from_z_radians(yaw))
    point_rotated = rotated_pose.apply(point_wrt_pose)
    return point_rotated
def get_rot_by_z_x_axes(x_axis, z_axis):
    normalize = lambda x: x/safe_2norm(x)
    z_axis = normalize(z_axis) #1
    y_axis = normalize(jnp.cross(z_axis, x_axis)) #2
    x_axis = normalize(jnp.cross(y_axis, z_axis)) #3
    return SO3.from_matrix(jnp.vstack([x_axis, y_axis, z_axis]).T)
def get_failure_sample(x):
    ee_pose = SE3(x[:7])
    p_elbow = x[7:10]
    p_wrist = x[10:13]
    shoulder_ref_pose = SE3.from_rotation_and_translation(
        get_rot_by_z_x_axes(jnp.array([1,0,0]), p_wrist-p_shoulder), p_shoulder)
    yaw1, yaw2 = np.random.normal(size=2) * jnp.pi*2/10
    p_wrist_fail = rotate_point_by_yaw(ee_pose, p_wrist, yaw1)
    p_elbow_fail = rotate_point_by_yaw(shoulder_ref_pose, p_elbow, yaw2)
    return jnp.hstack([x[:7], p_elbow_fail, p_wrist_fail])
def show_points(x):
    ee_pose = SE3(x[:7])
    p_elbow = x[7:10]
    p_wrist = x[10:13]
    shoulder.set_translate(p_shoulder)
    elbow.set_translate(p_elbow)
    wrist.set_translate(p_wrist)
    frame.set_pose(ee_pose)

In [352]:
#q = generate_random_joints(1)[0]
x = generate_successful_sample(panda_model.neutral)
x_fail = get_failure_sample(x)
show_points(x_fail)

In [353]:
def generate_random_joints(num_samples):
    return jnp.array(np.random.uniform(
        panda_model.lb[:7], panda_model.ub[:7], size=(num_samples,7)))
def generate_successful_sample(q):
    gripper_joints = jnp.full((2), 0.04)
    qnew = jnp.hstack([q, gripper_joints])
    fks = panda_model.fk_fn(qnew)
    ee_pose = fks[-1]
    p_elbow = fks[4][-3:]
    p_wrist = fks[5][-3:]
    #rtp = to_spherical_coord(p_elbow - p_shoulder)
    return jnp.hstack([ee_pose, p_elbow, p_wrist]) #p_wrist

@jax.jit
def get_batch_samples(qs):
    x_succ = jax.vmap(generate_successful_sample)(qs) #true data
    x_fail = jax.vmap(get_failure_sample)(x_succ)
    return x_succ, x_fail

In [677]:
from jax import random
hp = Hyperparam()
hp.dims = [13, 64, 64, 64, 64, 1]
hp.lr = 0.001
hp.batch_size = 128

model = get_mlp(hp)
key1, key2 = random.split(random.PRNGKey(0))
x = random.normal(key1, (hp.dims[0],))
params = model.init(key2, x)
tx = optax.adam(learning_rate=hp.lr)
state = TrainState.create(apply_fn=model.apply, params=params, tx=tx)

In [678]:
from jax import random
hp = Hyperparam()
hp.dims = [13, 64, 64, 64, 64, 7]
hp.lr = 0.001
hp.batch_size = 128

model_recon = get_mlp(hp)
key1, key2 = random.split(random.PRNGKey(0))
x = random.normal(key1, (hp.dims[0],))
params_recon = model_recon.init(key2, x)
tx_recon = optax.adam(learning_rate=hp.lr)
state_recon = TrainState.create(apply_fn=model_recon.apply, params=params_recon, tx=tx_recon)

In [679]:
def loss(state, params, x_succ, x_fail):
    logits_succ = state.apply_fn(params, x_succ).flatten()
    loss_succ = optax.sigmoid_binary_cross_entropy(
        logits_succ, jnp.ones_like(logits_succ)).mean()
    logits_fail = state.apply_fn(params, x_fail).flatten()
    loss_fail = optax.sigmoid_binary_cross_entropy(
        logits_fail, jnp.zeros_like(logits_fail)).mean()
    return loss_succ + loss_fail, (loss_succ, loss_fail)
grad_fn = jax.value_and_grad(loss, argnums=1, has_aux=True)

@jax.jit
def training_step(state, x_succ, x_fail):
    (loss, (loss_succ, loss_fail)), grads = grad_fn(state, state.params, x_succ, x_fail)
    state = state.apply_gradients(grads=grads)
    return state, loss, loss_succ, loss_fail

In [684]:
def loss_recon(state, params, x_succ, qs):
    qs_pred = state.apply_fn(params, x_succ)
    loss = optax.l2_loss(qs_pred, qs)
    return loss.mean()
grad_fn_recon = jax.value_and_grad(loss_recon, argnums=1)

@jax.jit
def training_step_recon(state, x_succ, qs):
    loss, grads = grad_fn_recon(state, state.params, x_succ, qs)
    state = state.apply_gradients(grads=grads)
    return state, loss

In [685]:
for epoch in range(50000):
    qs = qs = generate_random_joints(128)
    x_succ, x_fail = get_batch_samples(qs)
    state, loss, loss_succ, loss_fail = training_step(state, x_succ, x_fail)
    state_recon, loss_recon = training_step_recon(state_recon, x_succ, qs)
    if epoch % 100 == 0:
        print(f"epoch:{epoch}, loss:{loss}")
        print(f"loss_succ{loss_succ}, loss_fail:{loss_fail}, loss_recon:{loss_recon}")
        #print(f"loss_succ{loss_succ}, loss_fail:{loss_fail}")

epoch:0, loss:1.3868772983551025
loss_succ0.666491687297821, loss_fail:0.7203856706619263, loss_recon:1.4551236629486084
epoch:100, loss:1.372450590133667
loss_succ0.7001367807388306, loss_fail:0.6723138093948364, loss_recon:0.9212878346443176
epoch:200, loss:1.3592450618743896
loss_succ0.630511999130249, loss_fail:0.7287330627441406, loss_recon:0.8050041794776917
epoch:300, loss:1.354374647140503
loss_succ0.6517248153686523, loss_fail:0.7026497721672058, loss_recon:0.836265504360199
epoch:400, loss:1.359317421913147
loss_succ0.7630115151405334, loss_fail:0.5963059067726135, loss_recon:0.7451563477516174
epoch:500, loss:1.3375091552734375
loss_succ0.7079915404319763, loss_fail:0.629517674446106, loss_recon:0.7390410304069519
epoch:600, loss:1.3500193357467651
loss_succ0.700930118560791, loss_fail:0.6490892171859741, loss_recon:0.7413157224655151
epoch:700, loss:1.322577953338623
loss_succ0.5625837445259094, loss_fail:0.7599942088127136, loss_recon:0.773711621761322
epoch:800, loss:1.26

KeyboardInterrupt: 

In [686]:
trained_param = state.params

In [687]:
#show_fk(panda_model.neutral)
x = generate_successful_sample(panda_model.neutral[:7])
ee_pose = SE3(x[:7])
p_ee = x[4:7]
p_elbow = x[7:10]
p_wrist = x[10:13]
ee_z = ee_pose.as_matrix()[:3, 2]
proj_wrist = jnp.dot(p_ee-p_wrist, ee_z)

In [688]:
from sdf_world.nlp import *

In [711]:
prob = NLP()
lb = jnp.hstack([-1, -1, -1, -1, ws_lb, ws_lb, ws_lb])
ub = jnp.hstack([1, 1, 1, 1, ws_ub, ws_ub, ws_ub])
prob.add_var("x", 13, lb, ub)

In [712]:
#generate prob
q = generate_random_joints(1)[0]
x = generate_successful_sample(q)
ee_pose_target = SE3(x[:7])
show_fk(q)

In [713]:
def geometric_error(x):
    ee_pose = SE3(x[:7]).normalize()
    p_ee = x[4:7]
    p_elbow = x[7:10]
    p_wrist = x[10:13]
    #wrist
    ee_z = ee_pose.as_matrix()[:3, 2]
    err_proj_wrist = (jnp.dot(p_ee-p_wrist, ee_z) - proj_wrist)
    err_upper_arm = (safe_2norm(p_shoulder - p_elbow) - upper_arm_len)
    err_lower_arm = (safe_2norm(p_elbow - p_wrist) - lower_arm_len)
    err_hand = (safe_2norm(p_wrist - p_ee) - hand_len)
    err = jnp.hstack([err_proj_wrist, err_upper_arm, err_lower_arm,err_hand])
    return jnp.abs(err).max()
def kinematic_feasibility(x):
    ee_pose = SE3(x[:7]).normalize()
    x = jnp.hstack([ee_pose.parameters(), x[7:]])
    logit = model.apply(trained_param, x)
    return logit
def IKerror(x):
    ee_pose = SE3(x[:7]).normalize()
    err = safe_2norm((ee_pose_target.inverse()@ee_pose).log())
    return err

prob.add_objective(lambda x: jnp.array(0.))
prob.add_con("geom", 1, ["x"], geometric_error, 0.)
prob.add_con("kin", 1, ["x"], kinematic_feasibility, lower=0.)
prob.add_con("ikerr", 1, ["x"], IKerror, eq=0.)


In [714]:
prob.build()

In [715]:
x0 = np.random.uniform(lb, ub)
xsol, info = prob.solve(x0, viol_tol=0.01)

This is Ipopt version 3.14.10, running with linear solver MUMPS 5.2.1.

Number of nonzeros in equality constraint Jacobian...:       26
Number of nonzeros in inequality constraint Jacobian.:       13
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:       13
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       13
                     variables with only upper bounds:        0
Total number of equality constraints.................:        2
Total number of inequality constraints...............:        1
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  0.0000000e+00 1.68e+00 9.99e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00 

In [705]:
show_points(xsol)

In [706]:
q = model_recon.apply(state_recon.params, xsol)

In [707]:
panda.set_joint_angles(jnp.hstack([q,0.04,0.04]))

In [698]:
geometric_error(xsol)

Array(0.00643806, dtype=float32)

In [659]:
show_points(xsol)

In [655]:
x = xsol
ee_pose = SE3(x[:7]).normalize()
p_ee = x[4:7]
p_elbow = x[7:10]
p_wrist = x[10:13]

normalize = lambda x: x/safe_2norm(x)
y_axis = -normalize(p_elbow - p_shoulder)
x_axis = jnp.hstack([0., 0., (p_wrist - p_elbow)[-1]]) #temporary
z_axis = normalize(jnp.cross(x_axis, y_axis))
x_axis = jnp.cross(y_axis, z_axis)
rot_mat = jnp.vstack([x_axis, y_axis, z_axis]).T
rot = SO3.from_matrix(rot_mat)
shoulder_ref_frame = SE3.from_rotation_and_translation(rot, p_shoulder)

In [660]:
def gen_ref_rot(z_axis, x_axis):
    normalize = lambda x: x/safe_2norm(x)
    z_axis = normalize(z_axis)
    y_axis = normalize(jnp.cross(z_axis, x_axis))
    x_axis = jnp.cross(y_axis, z_axis)
    rot_mat = jnp.vstack([x_axis, y_axis, z_axis]).T
    return SO3.from_matrix(rot_mat)

vec = (p_elbow - p_shoulder)
ref_frame = SE3.from_rotation_and_translation(
    gen_ref_rot(p_elbow-p_shoulder, jnp.array([1,0,0.])), p_shoulder)
p_3 = ref_frame.apply(p_3_wrt_ref)
#q1
xy = (p_3 - p_shoulder)[:-1]
q1 = jnp.arctan2(xy[1], xy[0])
q2 = jnp.arctan2(jnp.linalg.norm((p_3 - p_shoulder)[:2]), 
                 (p_3 - p_shoulder)[2])
q3 = 


#frame.set_pose(SE3(fks[1]))

In [672]:
point.set_translate(p_3)

In [657]:
wrist.set_translate(p_3)

In [671]:
panda.set_joint_angles(jnp.array([q1,q2,-0.9,0,0,0,0,0,0.]))

In [575]:
rotated = SE3(fks[2]).inverse()@shoulder_ref_frame

In [598]:
from scipy.spatial.transform import Rotation

In [602]:
r, y, p = Rotation.from_matrix(rotated.rotation().as_matrix()
                               ).as_euler("yzx")

In [645]:
fks = panda_model.fk_fn(jnp.array([0.,0,0,0,0,0,0,0,0]))
p_elbow = fks[4][-3:]
p_3 = fks[3][-3:]
ref_frame = SE3.from_rotation_and_translation(
    gen_ref_rot(p_elbow-p_shoulder, jnp.array([1,0,0.])), p_shoulder)
p_3_wrt_ref = ref_frame.inverse().apply(p_3)

In [637]:
elbow.set_translate(p_elbow)

In [644]:
frame.set_pose(ref_frame)

In [593]:
frame.set_pose(SE3(fks[2]))

In [12]:
qs = np.random.uniform(panda_model.lb[:7], panda_model.ub[:7], size=(128,7))
x_succ, x_fail = get_batch_samples(qs)

In [13]:
bools = nn.sigmoid(model.apply(trained_param, x_fail)) > 0.5
jnp.arange(len(x_fail))[bools.flatten()]

Array([  1,   8,   9,  33,  53, 120, 123], dtype=int32)

In [102]:
# def feasibility(ee_pose, p_elbow, p_wrist):
#     ee_posevec = ee_pose.parameters()
#     return model.apply(trained_param, jnp.hstack([ee_posevec, p_elbow, p_wrist]))

# problem
qrand = np.random.uniform(panda_model.lb, panda_model.ub)
fks = panda_model.fk_fn(qrand)
pose_rand = SE3(fks[-1])
p_wrist = fks[5][-3:]

#vis
frame.set_pose(pose_rand)
panda.set_joint_angles(qrand)

In [56]:

# sphere_samples = fibonacci_sphere(1000)
# sphere_shoulder = sphere_samples * upper_arm_len + p_shoulder

logits = jax.vmap(feasibility, in_axes=(None, 0, None))(
    pose_rand, shoulder_sphere_points, p_wrist)
indices = np.arange(len(logits))[logits.flatten() > 0.]
elbow_points = np.array(shoulder_sphere_points[indices], dtype=np.float64)
elbow.set_translate(p_wrist)

# cond
#lower_arm_err = jnp.abs(jnp.linalg.norm(elbow_points - p_wrist, axis=-1) - lower_arm_len)
#elbow_points = elbow_points[lower_arm_err < 0.005]
nn.sigmoid(logits[indices].flatten())

#vis
colors = np.tile(Colors.read("blue", return_rgb=True), len(elbow_points)).reshape(-1, 3)
pc = PointCloud(world.vis, "pc", elbow_points, color="blue")

In [54]:
del pc

In [114]:


# def error_wrist_radius(x):
#     p_ee = x[4:7]
#     p_wrist = x[10:13]
#     err_wrist = safe_2norm(p_wrist - p_ee) - lower_arm_len
#     return jnp.abs(err_wrist)
# def error_mid_radius(x):

def feasibility(x):
    ee_pose = SE3(x[:7]).normalize()
    x = jnp.hstack([ee_pose.parameters(), x[7:]])
    logit = model.apply(trained_param, x)
    return - logit
def error_ee(x):
    ee_pose_curr = SE3(x[:7]).normalize()
    return safe_2norm((pose_rand.inverse()@ee_pose_curr).log())

prob.add_con("elbow_radius", 1, ["x"], error_radius, upper=0.01)
#prob.add_con("wrist_radius", 1, ["x"], error_wrist_radius, upper=0.01)
prob.add_con("fk_feas", 1, ["x"], feasibility, lower=0.)
prob.add_objective(error_ee)

In [115]:
prob.build()

In [119]:
x0 = np.random.uniform(lb, ub)

In [120]:
xsol, info = prob.solve(x0, viol_tol=0.001)

This is Ipopt version 3.14.10, running with linear solver MUMPS 5.2.1.

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:       26
Number of nonzeros in Lagrangian Hessian.............:        0

Total number of variables............................:       13
                     variables with only lower bounds:        0
                variables with lower and upper bounds:       13
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        2
        inequality constraints with only lower bounds:        1
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        1

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  2.4088335e+00 4.52e+00 9.96e-01   0.0 0.00e+00    -  0.00e+00 0.00e+00 

In [144]:
x = xsol
p_ee = x[4:7]
p_elbow = x[7:10]
p_wrist = x[10:13]
err_upper = safe_2norm(p_shoulder - p_elbow) - upper_arm_len
err_lower = safe_2norm(p_wrist - p_ee) - hand_len
err_mid = safe_2norm(p_elbow - p_wrist) - lower_arm_len
err_upper, err_lower, err_mid

(Array(0.00592175, dtype=float32),
 Array(-0.00012724, dtype=float32),
 Array(0.00338504, dtype=float32))

In [143]:
safe_2norm(p_wrist - p_ee)-hand_len

Array(-0.00012724, dtype=float32)

In [142]:
hand_len

Array(0.2295386, dtype=float32)

In [134]:
jnp.linalg.norm(ee_pose.translation() - p_wrist)

Array(0.22941135, dtype=float32)

In [128]:
safe_2norm(p_wrist - p_ee) - hand_len

Array(0.91949075, dtype=float32)

In [123]:
feasibility(xsol)

Array([16.513062], dtype=float32)

In [135]:
error_radius(xsol)

Array(0.00943403, dtype=float32)

In [130]:
ee_pose = SE3(xsol[:7]).normalize()
p_elbow = xsol[7:10]
p_wrist = xsol[10:]
frame.set_pose(ee_pose)
elbow.set_translate(p_elbow)
wrist.set_translate(p_wrist)

In [86]:
elbow.set_translate([0,0,0])

In [99]:
error_elbow_radius(xsol)

Array(0.00091258, dtype=float32)

In [100]:
error_wrist_radius(xsol)

Array(0.00994909, dtype=float32)

In [98]:
feasibility(xsol)

Array([27.751844], dtype=float32)

In [91]:
elbow = Sphere(world.vis, "elbow", 0.07, "blue", 0.5)

In [79]:
wrist = Sphere(world.vis, "wrist", 0.07, "red", 0.5)

In [165]:
lower_arm_err<0.001

Array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False], dtype=bool)

In [163]:
lower_arm_err.min()

Array(8.234382e-05, dtype=float32)

In [155]:
lower_arm_lens.max()

Array(0.00815082, dtype=float32)

In [155]:
world.vis["pc"].delete()

In [72]:
save("elbow_feas_net_euclid.pth", state, hp, force=True)

In [73]:
feas_fn = get_mlp_by_path("elbow_feas_net_euclid.pth")

In [61]:
from sdf_world.sdf_world import *
world = SDFWorld()

You can open the visualizer by visiting the following URL:
http://127.0.0.1:7004/static/


In [62]:
world.show_in_jupyter()

In [63]:
#panda_model = RobotModel(PANDA_URDF, PANDA_PACKAGE)
panda = Robot(world.vis, "panda", panda_model)

In [64]:
frame = Frame(world.vis, "frame", 0.2)
shoulder = Sphere(world.vis, "shoulder", 0.1, "red", 0.5)
elbow = Sphere(world.vis, "elbow", 0.1, "red", 0.5)
wrist = Sphere(world.vis, "wrist", 0.1, "red", 0.5)

In [65]:
#predefine
fks = panda_model.fk_fn(panda_model.neutral)
ee_pose = SE3(fks[-1])
# wrist_pos = panda_model.fk_fn(panda_model.neutral)[7][-3:]
# wrist_wrt_ee = ee_pose.inverse().apply(wrist_pos)
upper_arm_len = jnp.linalg.norm(fks[3][-3:] - fks[1][-3:])
p_shoulder = fks[1][-3:]
ws_lb = [-0.8, -0.8, -0.3]
ws_ub = [0.8, 0.8, 1.3]

In [153]:
sphere_points = fibonacci_sphere() * upper_arm_len + p_shoulder
# elbow_params = np.random.uniform([0., -np.pi], [np.pi, np.pi], size=(100,2))
elbow_points = jnp.array(sphere_points)
def feasibility_logit_fn(ee_posevec, elbow_param):
    return feas_fn(jnp.hstack([ee_posevec, elbow_param]))
@jax.jit
def ik(ee_pose):
    rot6d = ee_pose.as_matrix()[:3,:2].T.flatten()
    p_ee = ee_pose.translation()
    ee_posevec = jnp.hstack([rot6d, p_ee])
    logits = jax.vmap(feasibility_logit_fn, in_axes=(None, 0))(ee_posevec, elbow_points)
    return logits

In [154]:
cond = (ik(ee_pose) > 1.).flatten()
indices = jnp.arange(len(cond))[cond]
elbows = elbow_points[indices]

In [291]:
def ee_error(q, ee_pose_des):
    fks = panda_model.fk_fn(q)
    ee_pose_curr = SE3(fks[-1])
    ee_err_vec = (ee_pose_curr.inverse() @ ee_pose_des).log()
    ee_err = safe_2norm(ee_err_vec)
    return ee_err
def elbow_err(q, p_elbow_des):
    fks = panda_model.fk_fn(q)
    p_elbow_curr = fks[4][-3:]
    elbow_err = safe_2norm(p_elbow_curr - p_elbow_des)
    return elbow_err
err_grad_fn = jax.grad(ee_error)
elbowerr_grad_fn = jax.grad(elbow_err)

In [310]:
def get_jacobian(q):
    fks = panda_model.fk_fn(q)
    pos_jac = []
    rot_jac = []
    p_ee = fks[-1][-3:]
    for i in range(1, 8):
        p_frame = fks[i][-3:]
        rot_axis = SE3(fks[i]).as_matrix()[:3, 2]
        lin_vel = jnp.cross(rot_axis, p_ee - p_frame)
        pos_jac.append(lin_vel)
        rot_jac.append(rot_axis)
        
    pos_jac = jnp.vstack(pos_jac).T
    rot_jac = jnp.vstack(rot_jac).T
    return jnp.vstack([pos_jac, rot_jac])

In [156]:
p_elbow = elbows[1]
elbow.set_translate(p_elbow)

In [158]:
q = panda_model.neutral
panda.set_joint_angles(q)

In [401]:
ee_grad = err_grad_fn(q, pose_rand)
elbow_grad = elbowerr_grad_fn(q, p_elbow)

jac = get_jacobian(q)
ns_proj = jnp.eye(7) - jac.T@jac
q_delta = ee_grad + jnp.hstack([ns_proj@elbow_grad[:-2],0,0])
q = q - q_delta*0.2
panda.set_joint_angles(q)

In [183]:
q_grad

Array([ 0.07283606,  0.00364066,  0.0863461 , -0.08738822, -0.08824547,
        0.10718858,  0.20078273,  0.        ,  0.        ], dtype=float32)

In [65]:
far_points = farthest_point_sampling(points, 5)

In [99]:
p_elbow = far_points[0]

In [76]:
panda = Robot(world.vis, "panda", panda_model)
panda.reduce_dim([7,8], [0.04, 0.04])
frame_elbow = Frame(world.vis, "elbow_frame", 0.2)
elbow = Sphere(world.vis, "elbow", 0.1, "red", 0.5)

In [101]:
frame_1 = Frame(world.vis, "frame1", 0.2)

In [81]:
panda.set_joint_angles(panda_model.neutral[:7])

In [107]:
fks = panda_model.fk_fn(panda_model.neutral)
pose2 = SE3(fks[2])
pose5 = SE3(fks[5])
frame_1.set_pose(pose2)
frame_elbow.set_pose(pose5)

In [120]:
diff = (pose5.translation() - pose2.translation())
y_pose2 = pose2.as_matrix()[:3,1]

In [144]:
p_elbow = (diff @ y_pose2) * y_pose2 + pose2.translation()
ee_pose = SE3(fks[-1])
alpha_len = jnp.linalg.norm(p_elbow - fks[-6][-3:])
beta_len = jnp.linalg.norm(ee_pose.translation() - fks[-6][-3:])

In [132]:
frame.set_pose(ee_pose)

In [187]:
# given p_elbow, ee_pose, can we solve ik?
v = ee_pose.translation() - p_elbow
c = jnp.linalg.norm(v)
r = jnp.sqrt((beta_len**2 + c**2 - alpha_len**2)/(2*c**2))

In [190]:
# z_ee = ee_pose.as_matrix()[:3, 2]
# up_vec = jnp.cross(v, jnp.cross(v, z_ee))
# up_vec = up_vec/jnp.linalg.norm(up_vec)
# up_mag = jnp.sqrt(alpha_len**2 - (c*r)**2)
p_wrist = p_elbow + r*v #+up_vec*up_mag

In [191]:
wrist.set_translate(p_wrist)

In [158]:
v

Array([ 6.1263674e-01,  1.1562403e-08, -1.7700875e-01], dtype=float32)

In [139]:
wrist.set_translate(fks[-6][-3:])

In [129]:
elbow.set_translate(p_elbow)

In [112]:
diff

Array([4.6650025e-01, 5.9267933e-09, 3.9849854e-01], dtype=float32)

In [80]:
panda.set_joint_angles(jnp.array([0,-0.5,0,0,0,0,0]))

In [70]:
elbow.set_translate(far_points[4])